version: '3.8'

services:
#  app:
#    build: app
#    restart: always
#    ports:
#      - 8080:8080
#    depends_on:
#      - pg_db
#      - jaeger
#    environment:
#      - JAEGER_SERVICE_NAME=hello_service
#      - JAEGER_AGENT_HOST=jaeger
#      - JAEGER_AGENT_PORT=6831
#      - JAEGER_SAMPLER_MANAGER_HOST_PORT=jaeger:5778

  pg_db:
    image: postgres:13.1
    restart: always
    ports:
      - 5432:5432
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password

  jaeger:
    image: jaegertracing/all-in-one:latest
    ports:
      - "5775:5775/udp"
      - "6831:6831/udp"
      - "6832:6832/udp"
      - "5778:5778"
      - "16686:16686"
      - "14268:14268"
      - "9411:9411"
