route:
  receiver: 'telegram'
  # receiver: 'default-receiver'
  # group_wait: 30s
  # group_interval: 5m
  # repeat_interval: 4h
  # group_by: [cluster, alertname]
  
  #routes:
  # - receiver: 'telegram'
  #   group_wait: 10s
  #   match_re:
  #     alertname: ".*"
  #   continue: true

  # - receiver: 'rocketchat'
  #   group_wait: 10s
  #   match_re:
  #     alertname: ".*"
  #   continue: true

receivers:
  - name: 'telegram'
  # - name: 'default-receiver'
  #   email_configs:
  #   - to: 'example_email_group@example.org'
  # - name: telegram
  #   webhook_configs:
  #   - send_resolved: true
  #     url: http://127.0.0.1:9087/alert/-chat_id
  # - name: rocketchat
  #   webhook_configs:
  #   - send_resolved: true
  #     url: http://127.0.0.1:9087/alert/'${WEBHOOK_URL}'